version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ilyaart/api_yamdb:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/html/static
      - media_volume:/var/html/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
volumes:
  media_volume:
  static_volume:
