name: new workflow
on: [push]
jobs:
  smoke_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9" ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with: 
        python-version: ${{ matrix.python-version }}
    - name: install dependency
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установка зависимостей
        pip install -r ./api_yamdb/requirements.txt 
 
    - name: test with flake
      run: |
        python -m flake8
        pytest

  build_and_push:
    runs-on: ubuntu-latest
    needs: smoke_test
    if: github.ref == 'refs/heads/master'
    steps:
    - name: check out
      uses: actions/checkout@v2
    - name: build docker image
      uses: docker/setup-buildx-action@v1
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      uses: docker/build-push-action@v2
      with:
        context: ./api_yamdb
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/api_yamdb:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - name: ssh connect
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key:  ${{ secrets.SSH_KEY }}
        script: |
          sudo docker-compose stop
          sudo docker-compose rm web
          echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          sudo docker-compose up -d

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.action }} action triggered a build process.
            Build has completed successfully.
            

